# Generated by Django 6.0 on 2025-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='status',
            field=models.CharField(choices=[('planned', 'В планах'), ('watched', 'Переглянуто'), ('favorite', 'Улюблене')], default='planned', max_length=20),
        ),
    ]
